services:
  app:
    image: jhonatan25ls/movies-database:latest
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"