# Generated by Django 4.1 on 2024-04-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Indice_madurez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('cantidad_vistas', models.IntegerField()),
                ('argumento', models.CharField(max_length=255)),
                ('duracion', models.IntegerField()),
                ('fecha_publicacion', models.DateField()),
                ('imagen_cartelera', models.URLField(blank=True, null=True)),
                ('actor', models.ManyToManyField(to='movies.actor')),
                ('genero', models.ManyToManyField(to='movies.genero')),
                ('indice_madurez', models.ManyToManyField(to='movies.indice_madurez')),
            ],
        ),
    ]
