# Generated by Django 4.1 on 2024-04-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='actor',
            field=models.ManyToManyField(related_name='actors', to='movies.actor'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.ManyToManyField(related_name='generos', to='movies.genero'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='indice_madurez',
            field=models.ManyToManyField(related_name='indices', to='movies.indice_madurez'),
        ),
    ]
